
name: Teste WorkFlow


on:
  push:
    branches: [ "main", "developer" ]



jobs:
  test_job:
    name: Executanto job de teste
    runs-on: ubuntu-latest
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{ secrets.DATA_BASE }}
        ports:
          - 1433:1433
          
    steps:
    - name: Step 1
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:  
        dotnet-version: '8.0.x'
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:   
        username: 'antoniodevio'
        password: ${{ secrets.DOCKER_LOGIN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        file: testedocker.Dockerfile
        tags: 'antoniodevio/testearqui:latest'
        push: true

    - name: Run unit tests
      run: dotnet test
      env:
        ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=master;User Id=SA;Password=${{ secrets.DATA_BASE }};"

